name: Build Image

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: ubio/github-actions/.github/workflows/ci-build.yaml@master
    with:
      name: NodeScript Service Runner
      image: gcr.io/automation-cloud-registry/nodescript-service-runner
      ref: ${{ github.ref }}
      file: Dockerfile
    secrets:
      REGISTRY_SECRET: ${{ secrets.GCP_REGISTRY_ACCESS }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
